#!/bin/sh /etc/rc.common

### BEGIN INIT INFO
# Provides:          quectel-cm
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Quectel\ LTE\ module\ dial\ tool
### END INIT INFO

START=99

NAME=quectel-cm
SCRIPT="quectel-CM-start"

PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

start() {
	if [ -f $PIDFILE ] && [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE); then
		echo 'Service already running' >&2
		return 1
	fi
	echo 'Starting service…' >&2
	local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
	sh -c "$CMD" > "$PIDFILE"

	sleep 1
	PID=$(cat $PIDFILE)
	if [ -d "/proc/$PID/" ]; then
		echo "$NAME is now running, the PID is $PID"
	else
		echo "Error! Could not start $NAME!"
	fi
}

stop() {
	if [ ! -f "$PIDFILE" ]; then
		echo 'Service not running' >&2
		return 1
	fi

	PID=$(cat $PIDFILE)
	if [ ! -d "/proc/$PID/" ]; then
		echo 'Service not running' >&2
		return 1
	fi

	echo 'Stopping service...' >&2
	kill -12 $PID
				
	while true; do
		if [ -d "/proc/$PID/" ]; then
			sleep 1
		else
			break
		fi
	done
				
	rm -f "$PIDFILE"
	echo 'Service stopped' >&2
}

restart() {
	echo -e "AT+QSIMDET=1,1\r\n" > /dev/ttyUSB2 || true 
	sleep 1
	echo -e "AT+CFUN=1,1\r\n" >/dev/ttyUSB2 || true 
	stop
	start
}

uninstall() {
	echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
	local SURE
	read SURE
	if [ "$SURE" = "yes" ]; then
		stop
		rm -f "$PIDFILE"
		echo "Notice: log file was not removed: $LOGFILE" >&2
		update-rc.d -f $NAME remove
		rm -fv "$0"
	else
		echo "Abort!"
	fi
}

status() {
	printf "%-50s" "Checking $NAME..."
	if [ -f $PIDFILE ] && [ -s $PIDFILE ]; then
		PID=$(cat $PIDFILE)
		if [ ! -d "/proc/$PID/" ]; then
			printf "%s\n" "The process appears to be dead but pidfile still exists"
		else
			echo "Running, the PID is $PID"
		fi
	else
		printf "%s\n" "Service not running"
	fi
}
